Switch to using is_legacy for CI matrix

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -167,7 +167,7 @@ runs:
         fi
 
         if [ -z "$TOIT_BIN" ]; then
-          echo "TOIT binary not found in toit/bin" >&2
+          echo "Toit binary not found in toit/bin" >&2
           exit 1
         fi
 
